# fly.toml app configuration file generated for cold-sun-1757 on 2023-07-14T00:44:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-sun-1757"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
